#base image
FROM python:3.11

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY apps/api/requirements.txt .

RUN pip install --no--cahce-dir -requirements.txt

COPY  . .

EXPOSE 8000

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
